set nocompatible

filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'luispedro/vim-ipython'
Plugin 'tpope/vim-fugitive'
Plugin 'kevinw/pyflakes-vim'
Plugin 'gerw/vim-latex-suite'

call vundle#end()            " required
filetype plugin indent on
filetype on " detect the type of file

set ignorecase
set history=1000 " How many lines of history to remember
set cf " enable error files and error jumping
filetype plugin on " load filetype plugins
syntax enable
set hlsearch
let g:tex_flavor='latex'
let g:Tex_FoldedSections=''
let g:Tex_FoldedEnvironments=''
let g:Tex_FoldedMisc=''
if has("autocmd") && exists("+omnifunc")
    autocmd Filetype *
    	    \	if &omnifunc == "" |
    	    \		setlocal omnifunc=syntaxcomplete#Complete |
    	    \	endif
endif

set ts=4 sts=4 sw=4 expandtab smartindent

" the mouse mode just does not work well enough. Disable it.
set mouse=
set background=light
colorscheme desert
vnoremap < <gv
vnoremap > >gv

let mapleader=","
let maplocalleader=";"
nnoremap <leader>v V`]

" reflow paragaph
nnoremap <leader>q gqip
" New window & move focus there
nnoremap <leader>w <C-w>v<C-w>l


set undofile
set undodir=$HOME/.vim/undo " where to save undo histories
set undolevels=1000         " How many undos
set undoreload=10000        " number of lines to save for undo

" Make search default to global
set gdefault
set backspace=indent,eol,start

" Get rid of search highlighting
nnoremap <leader><space> :noh<cr>
