#!/usr/bin/env python
from os import popen
from os.path import exists
import re
import sys
pat = re.compile(r'([0-9]+)\.lanec1 +([0-9a-zA-Z]{8})\.[^ ]* *lcoelho.*([0-9:]{8}| {7}0) (R|S|Q).*')
doheader = sys.argv[0].find('nnqstat') == -1
cmdpat = None
if len(sys.argv) > 1:
    if sys.argv[1] in ('-h', '--help'):
        print '''\
nnqstat [pattern]

Print all jobs that match the regex `pattern`.
If pattern is not given, print all jobs.

Print Format
------------
Job ID      Queue ID      Time     Command

'''
        sys.exit(0)
    cmdpat = sys.argv[1]
try:
    input = popen('qstat')
    for line in input:
        if doheader:
            print '%-12s %-8s      %-8s        %s' % ('Job ID', 'Queue ID', 'Time', 'Command')
            print '-' * 50
            doheader = False
        M = pat.match(line)
        if M is None: continue
        jobid,qid,time,status = M.groups()
        cmdline = None
        if status == 'Q':
            time = '  Queued'
        cmdline = file('/home/lcoelho/.qarray-pid/%s.log' % qid).readlines()[0].strip()
        if cmdpat is not None and cmdline.find(cmdpat) == -1:
            continue
        print '%-12s %-8s      %-8s        %s' % (jobid, qid, time, cmdline)
except Exception,e:
    print e
