#!/usr/bin/env python

import sys
import os
from pipes import quote

def create_directories(dname):
    '''
    create_directories(dname)

    Recursively create directories.
    '''
    from os import path, mkdir, errno
    if dname.endswith('/'):
        dname = dname[:-1]
    if not dname:
        return
    head, tail = path.split(dname)
    if head: create_directories(head)
    try:
        mkdir(dname)
    except OSError, e:
        if e.errno != errno.EEXIST:
            raise

home = os.environ["HOME"]

def write_shell_script(args):
    command = " ".join(map(quote, args))
    outputname = home + '/.qarray-pid/scripts/q%s.sh' % os.getpid()
    logname = home + '/.qarray-pid/%s.log' % os.getpid()
    output = file(outputname, 'w')
    name = "_".join(args)
    name = name.replace(' ', '_')
    if name.startswith("jug_execute_"):
        name = "jug_" + name[len("jug_execute_"):]
    name = "%s.%s" % (os.getpid(),name)
    name = name[:15]
    print >>output, '''
#!/bin/bash
#
#PBS -N %s
#PBS -S /bin/bash
#PBS -V

#PBS -o q%s.stdout
#PBS -e q%s.stderr

''' % (name, os.getpid(), os.getpid())
    print >>output,'''

echo
echo
echo "HOSTNAME:$HOSTNAME"
echo
echo

cd %s

%s

# self-destruct
rm %s
rm %s

''' % (os.getcwd(), command, outputname, logname)
    output.close()

    log = file(logname, 'w')
    print >>log, command
    print >>log, outputname
    log.close()
    return outputname


def usage():
    print '''\
----------------------
Usage : qarray command
----------------------


EXAMPLES
   qarray command...
'''

def main():
    if len(sys.argv) == 1:
        usage()
        return
    command = sys.argv[1:]
    create_directories(home + '/.qarray-pid/scripts')
    script = write_shell_script(command)
    command = "qsub -V -q pool1 %s" % script
    #print command
    os.system(command)

if __name__ == '__main__':
    main()

